/*
 * Copyright (C) 2017 The "MysteriumNetwork/node" Authors.
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

package geodb

// generated by generator.go - DO NOT EDIT

// DbData holds base64 encoded GeoLite2 db binary data
const DbData = "" + dbDataPart0 + dbDataPart1 + dbDataPart2 + dbDataPart3 + dbDataPart4 + dbDataPart5 + dbDataPart6 + dbDataPart7 + dbDataPart8 + dbDataPart9 + dbDataPart10 + dbDataPart11 + dbDataPart12 + dbDataPart13 + dbDataPart14 + dbDataPart15 + dbDataPart16 + dbDataPart17 + dbDataPart18 + dbDataPart19 + dbDataPart20 + dbDataPart21 + dbDataPart22 + dbDataPart23 + dbDataPart24 + dbDataPart25 + dbDataPart26 + dbDataPart27 + dbDataPart28 + dbDataPart29 + dbDataPart30 + dbDataPart31 + dbDataPart32 + dbDataPart33 + dbDataPart34 + dbDataPart35 + dbDataPart36 + dbDataPart37 + dbDataPart38 + dbDataPart39 + dbDataPart40 + dbDataPart41 + dbDataPart42 + dbDataPart43 + dbDataPart44 + dbDataPart45 + dbDataPart46 + dbDataPart47 + dbDataPart48 + dbDataPart49 + dbDataPart50 + dbDataPart51 + dbDataPart52 + dbDataPart53 + dbDataPart54 + dbDataPart55 + dbDataPart56 + dbDataPart57 + dbDataPart58 + dbDataPart59 + dbDataPart60 + dbDataPart61 + dbDataPart62 + dbDataPart63 + dbDataPart64 + dbDataPart65 + dbDataPart66 + dbDataPart67
